version: "3.8"

services:
  app:
    build: .
    container_name: app
    volumes:
      - ./:/app
    environment:
      - name=value
    ports:
      - "3000:3000"
    networks:
      - my_network
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app-odev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"  
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
